### ISSUE TITLE
Display standalone actions

### ISSUE THREAD

**Issue by Flavien-Panunzio** [Lednerb/nova-action-button-selectors#1] opened 2023-10-30 08:14 UTC
I was on version 2.0.1 and all my standalone actions were displayed very well until then, however, since I updated your repo with composer ([v2.0.3](https://packagist.org/packages/lednerb/nova-action-button-selectors)), I no longer have a display of my standalone actions. It shouldn't be much, can you fix the problem?

**Comment by Lednerb** [comment] 2023-11-01 15:01
Hi @Flavien-Panunzio 

the problem should now be fixed in version v2.0.4.
Please update your dependencies and send me a quick notification if the problem is now fixed for you.

This repo will be archived afterwards because the repo is now hosted on codeberg:
https://codeberg.org/Lednerb/nova-action-button-selectors

**Closed as completed** 2023-11-01 15:07 UTC

**Comment by Flavien-Panunzio** [comment] 2023-11-02 08:09
I just tried to update the dependencies, I am in v2.0.4 but the button still disappears. I no longer have the "3 little dots" at the top left to choose my standalone action

**Comment by Lednerb** [comment] 2023-11-03 09:36
Thanks for your update.
It seems that this is related to:

https://codeberg.org/Lednerb/nova-action-button-selectors/issues/10

**Comment by Flavien-Panunzio** [comment] 2023-11-10 07:16
I understand, I will therefore stay in version 2.0.1 of your plugin which works perfectly regardless of the version of Nova, if you ever resolve the problem, please keep me informed so that I can update your plugin.
